config/routes.rb
Rails.application.routes.draw do
  resources :non_teches
  resources :teachers
  resources :students
  # get 'home/index'
  get 'home/about' #route
  root 'home#index' #for homepage

  post "/submit", to:"home#redirect"

  get "/success", to:"students#success"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/non_tech.rb
class NonTech < ApplicationRecord
    has_one_attached :aadhar_img
    has_one_attached :license_img
    has_one_attached :photo
    has_one_attached :registration_img    
end

app/models/student.rb
class Student < ApplicationRecord
    has_one_attached :aadhar_img
    has_one_attached :license_img
    has_one_attached :photo
    has_one_attached :registration_img    
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_one_attached :aadhar_img
    has_one_attached :license_img
    has_one_attached :photo
    has_one_attached :registration_img  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  Options = Hash["1"=>"Student","2"=>"Faculty","3"=>"Non-Teaching Staff","4"=>"Other"]
    
  def index
    
  end
  
  def about
  end

  def redirect
    puts params
    if params[:category]=="1"
      redirect_to "/students/new"
    elsif params[:category]=="2"
      redirect_to "/teachers/new"
    elsif params[:category]=="3"
      redirect_to "/non_teches/new"
    elsif params[:category]=="4"
      redirect_to "/"
    end
  
  end

end

app/controllers/non_teches_controller.rb
class NonTechesController < ApplicationController
  before_action :set_non_tech, only: %i[ show edit update destroy ]

  # GET /non_teches or /non_teches.json
  def index
    @non_teches = NonTech.all
  end

  # GET /non_teches/1 or /non_teches/1.json
  def show
  end

  # GET /non_teches/new
  def new
    @non_tech = NonTech.new
  end

  # GET /non_teches/1/edit
  def edit
  end

  def success
  end

  # POST /non_teches or /non_teches.json
  def create
    @non_tech = NonTech.new(non_tech_params)

    respond_to do |format|
      if @non_tech.save
        format.html { render :success, notice: "Non tech was successfully created." }
        format.json { render :show, status: :created, location: @non_tech }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @non_tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /non_teches/1 or /non_teches/1.json
  def update
    respond_to do |format|
      if @non_tech.update(non_tech_params)
        format.html { redirect_to non_tech_url(@non_tech), notice: "Non tech was successfully updated." }
        format.json { render :show, status: :ok, location: @non_tech }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @non_tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /non_teches/1 or /non_teches/1.json
  def destroy
    @non_tech.destroy

    respond_to do |format|
      format.html { redirect_to non_teches_url, notice: "Non tech was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_non_tech
      @non_tech = NonTech.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def non_tech_params
      params.require(:non_tech).permit(:name, :email, :office, :phone, :vehicle_no, :adhar_no, :license, :employee_no, :aadhar_img, :license_img, :photo, :registration_img)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  def success
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { render :success, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def success
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email, :department, :phone, :roll_no, :vehicle_no, :adhar_no, :license, :aadhar_img, :license_img, :photo, :registration_img)
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  def success 
  end

  

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { render :success, notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :department, :phone, :faculty_no, :adhar_no, :vehicle_no, :license, :aadhar_img, :license_img, :photo, :registration_img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/non_teches_helper.rb
module NonTechesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/about.html.erb
<h1> about.... </h1>

app/views/home/index.html.erb
<div class="d-flex justify-content-center align-items-center flex-column" style="height:100vh" >    
    <div>
        <div class="form-check d-flex align-items-center" style="gap:2%">
            <input class="form-check-input mb-2" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value="student" checked>
            <label class="form-check-label" for="flexRadioDefault1">
                <h3>Student</h3>
            </label>
        </div>
        <div class="form-check d-flex align-items-center" style="gap:2%">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" value="faculty">
            <label class="form-check-label" for="flexRadioDefault2">
                <h3>Faculty</h3>
            </label>
        </div>
        <div class="form-check d-flex align-items-center" style="gap:2%,width:50px">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" value="non-tech">
            <div class="d-flex">
            <label class="form-check-label" for="flexRadioDefault3">
                <h3>Non-Technical Staff</h3>
            </label>
            </div>
        </div>
        <div class="form-check d-flex align-items-center" style="gap:2%">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault4" value="other" >
            <label class="form-check-label" for="flexRadioDefault4">
                <h3>Others</h3>
            </label>
        </div>
    </div>
    
   <button type="button" id="submit" class="btn btn-primary" onclick="redirect()" >Proceed</button> 
   
    <%# <%= link_to 'Proceed',$value,class:"btn btn-primary" %>
   
   
  
</div>
<%# <script>
document.getElementById('submit').onclick = function() {
    var radios = document.getElementsByName('flexRadioDefault');
    for (var radio of radios)
    {
        if (radio.checked) {
            if(radio.value=='student')
            // window.location.href="/students/new"
            {
                <%controller.redirect_to "/students/new" %> 
            }
            else if(radio.value=='faculty')
            
            else if(radio.value=='non-tech')
            
            else if(radio.value=='other')
            
        }
    }
}
</script> %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registration Form</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
  <%= yield %> <!-- yield here is actually the index file -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/non_teches/_form.html.erb
<div class="container w-50">
<%= form_with(model: non_tech) do |form| %>
  <% if non_tech.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(non_tech.errors.count, "error") %> prohibited this non_tech from being saved:</h2>

      <ul>
        <% non_tech.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 form-group">
    <%= form.label :name, style: "display: block" ,class:"form-label" %>
    <%= form.text_field :name,class:"form-control",required:true %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :email,"Email Address", style: "display: block" %>
    <%= form.text_field :email,class:"form-control",required:true %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :office, style: "display: block" %>
    <%= form.text_field :office ,class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :phone,"Mobile No.", style: "display: block" %>
    <%= form.text_field :phone,class:"form-control" ,required:true,maxlength:10%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :employee_no,"Employee No.", style: "display: block" %>
    <%= form.text_field :employee_no,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :photo, "Upload Photo Here"%>
    <%= form.file_field :photo, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :vehicle_no,"Vehicle Registration No.", style: "display: block" %>
    <%= form.text_field :vehicle_no,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :registration_img, "Upload Vehicle Registration Certificate Here"%>
    <%= form.file_field :registration_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :adhar_no,"Aadhar No.", style: "display: block" %>
    <%= form.text_field :adhar_no,class:"form-control" ,required:true,maxlength:12%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :aadhar_img, "Upload Aadhar Here"%>
    <%= form.file_field :aadhar_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :license,"Driving License No.", style: "display: block" %>
    <%= form.text_field :license,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :license_img, "Upload Driving License Here"%>
    <%= form.file_field :license_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 d-flex justify-content-center">
    <%= form.submit "Make Request", class:"btn btn-success"  %>
  </div>
<% end %>
</div>

app/views/non_teches/_non_tech.html.erb
<div id="<%= dom_id non_tech %>">
  <p>
    <strong>Name:</strong>
    <%= non_tech.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= non_tech.email %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= non_tech.office %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= non_tech.phone %>
  </p>

  <p>
    <strong>Roll no:</strong>
    <%= non_tech.employee_no %>
  </p>

  <p>
    <strong>Vehicle no:</strong>
    <%= non_tech.vehicle_no %>
  </p>

  <p>
    <strong>Adhar no:</strong>
    <%= non_tech.adhar_no %>
  </p>

  <p>
    <strong>License:</strong>
    <%= non_tech.license %>
  </p>

    <% if non_tech.aadhar_img.attached? %>
      <%= image_tag non_tech.aadhar_img %>
    <%end%>

    <% if non_tech.license_img.attached? %>
      <%= image_tag non_tech.license_img %>
    <%end%>

    <% if non_tech.photo.attached? %>
      <%= image_tag non_tech.photo %>
    <%end%>

    <% if non_tech.registration_img.attached? %>
      <%= image_tag non_tech.registration_img %>
    <%end%>


    
          

</div>

app/views/non_teches/edit.html.erb
<h1>Editing non tech</h1>

<%= render "form", non_tech: @non_tech %>

<br>

<div>
  <%= link_to "Show this non tech", @non_tech %> |
  <%= link_to "Back to non teches", non_teches_path %>
</div>

app/views/non_teches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>non_teches</h1>


<div id="non_teches">
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Department</th>
        <th>Phone</th>
        <th>Rollno</th>
        <th>vehicle_no</th>
        <th>adhar_no</th>
        <th>license</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>

      <% @non_teches.each do |non_tech| %>
       
        <tr>
          <td><%= link_to non_tech.name, non_tech %></td>
          <td><%= non_tech.email %></td>
          <td><%= non_tech.phone %></td>
          <td><%= non_tech.office %></td>
          <td><%= non_tech.employee_no %></td>
          <td><%= non_tech.vehicle_no %></td>
          <td><%= non_tech.adhar_no %></td>
          <td><%= non_tech.license %></td>
          
        <% if non_tech.aadhar_img.attached? %>
          <%= image_tag non_tech.aadhar_img ,style:"width:200px"%>
        <%end%>
    
        <% if non_tech.license_img.attached? %>
          <%= image_tag non_tech.license_img ,style:"width:200px" %>
        <%end%>
          
        <% if non_tech.license_img.attached? %>
          <%= image_tag non_tech.photo ,style:"width:200px" %>
        <%end%>

        <% if non_tech.license_img.attached? %>
          <%= image_tag non_tech.registration_img  ,style:"width:200px"%>
        <%end%>
  
          
        <td><%= link_to 'Delete', non_tech, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
       
      <% end %>
    </tbody>
  </table>
</div>

app/views/non_teches/new.html.erb
<div class="d-flex justify-content-center mt-4 mb-3">
  <h1>
    Vehicle Sticker Request
  </h1>
</div>

<%= render "form", non_tech: @non_tech %>

app/views/non_teches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @non_tech %>

<div>
  <%= link_to "Edit this non tech", edit_non_tech_path(@non_tech) %> |
  <%= link_to "Back to non teches", non_teches_path %>

  <%= button_to "Destroy this non tech", @non_tech, method: :delete %>
</div>

app/views/non_teches/success.html.erb
<div class="d-flex align-items-center justify-content-center w-100" style="height:100vh">
    <div class="alert alert-success" role="alert">
        Your Request has been submitted. It has been forwared to the Dean (Faculty Welfare).
    </div>
</div>

app/views/students/_form.html.erb
<div class="container w-50">
<%= form_with(model: student,local: true) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red" class="mb-3">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 form-group">
    <%= form.label :name, style: "display: block" ,class:"form-label" %>
    <%= form.text_field :name,class:"form-control",required:true %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :email,"Email Address", style: "display: block" %>
    <%= form.text_field :email,class:"form-control",required:true %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :department, style: "display: block" %>
    <%= form.text_field :department ,class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :phone,"Mobile No.", style: "display: block" %>
    <%= form.text_field :phone,class:"form-control" ,required:true,maxlength:10%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :roll_no,"Roll No.", style: "display: block" %>
    <%= form.text_field :roll_no,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :photo, "Upload Photo Here"%>
    <%= form.file_field :photo, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :vehicle_no,"Vehicle Registration No.", style: "display: block" %>
    <%= form.text_field :vehicle_no,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :registration_img, "Upload Vehicle Registration Certificate Here"%>
    <%= form.file_field :registration_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :adhar_no,"Aadhar No.", style: "display: block" %>
    <%= form.text_field :adhar_no,class:"form-control" ,required:true,maxlength:12%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :aadhar_img, "Upload Aadhar Here"%>
    <%= form.file_field :aadhar_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :license,"Driving License No.", style: "display: block" %>
    <%= form.text_field :license,class:"form-control" ,required:true%>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :license_img, "Upload Driving License Here"%>
    <%= form.file_field :license_img, class:"form-control",required:true%>
  </div>

  <div class="mb-3 d-flex justify-content-center">
    <%= form.submit "Make Request", class:"btn btn-success"  %>
  </div>
<% end %>
</div>

  

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
   
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
      <p>
      <strong>Name:</strong>
      <%= student.name %>
      </p>
    </h1>
    <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= student.department %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Roll no:</strong>
    <%= student.roll_no %>
  </p>

  <p>
    <strong>Vehicle no:</strong>
    <%= student.vehicle_no %>
  </p>

  <p>
    <strong>Adhar no:</strong>
    <%= student.adhar_no %>
  </p>

  <p>
    <strong>License:</strong>
    <%= student.license %>
  </p>
  </div>

  <p class="p-5">
  <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">AADHAR</a>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">LICENSE</button>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample3" aria-expanded="false" aria-controls="multiCollapseExample3">PHOTO</button>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample4" aria-expanded="false" aria-controls="multiCollapseExample4">REGISTRATION</button>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">HIDE/SHOW</button>
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample1">
      <div class="card card-body">
         <% if student.aadhar_img.attached? %>
      <%= image_tag student.aadhar_img ,class:"img-fluid"  %>
    <%end%>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample2">
      <div class="card card-body">
       <% if student.license_img.attached? %>
      <%= image_tag student.license_img ,class:"img-fluid"  %>
    <%end%>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample3">
      <div class="card card-body">
        <% if student.photo.attached? %>
      <%= image_tag student.photo ,class:"img-fluid" %>
    <%end%>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample4">
      <div class="card card-body">
        <% if student.registration_img.attached? %>
          <%= image_tag student.registration_img ,class:"img-fluid" %>
        <%end%>
      </div>
    </div>
  </div>
</div>   


</div>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>


<div id="students">
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Department</th>
        <th>Phone</th>
        <th>Rollno</th>
        <th>vehicle_no</th>
        <th>adhar_no</th>
        <th>license</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>

      <% @students.each do |student| %>
       
        <tr>
          <td><%= link_to student.name, student %></td>
          <td><%= student.email %></td>
          <td><%= student.phone %></td>
          <td><%= student.department %></td>
          <td><%= student.roll_no %></td>
          <td><%= student.vehicle_no %></td>
          <td><%= student.adhar_no %></td>
          <td><%= student.license %></td>
          

        <% if student.aadhar_img.attached? %>
          <% image_tag student.aadhar_img ,style:"width:200px"%>
        <%end%>
    
        <% if student.license_img.attached? %>
          <% image_tag student.license_img ,style:"width:200px" %>
        <%end%>
          
        <% if student.license_img.attached? %>
          <% image_tag student.photo ,style:"width:200px" %>
        <%end%>

        <% if student.license_img.attached? %>
          <% image_tag student.registration_img  ,style:"width:200px"%>
        <%end %>

          
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
       
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<div class="d-flex justify-content-center mt-4 mb-3">
  <h1>
    Vehicle Sticker Request
  </h1>
</div>

<%= render "form", student: @student %>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div class="p-1" >
  <%= link_to "Edit this student", edit_student_path(@student),class:"btn btn-secondary p-2 m-2" %>
  <%= link_to "Back to students", students_path,class:"btn btn-secondary p-2 m-2" %>
  <%= button_to "Destroy this student", @student, method: :delete, class:"btn btn-danger m-4" %>
</div>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>